---

- hosts: all
  become: true
  tasks:

  - name: install latest apache package with php
    yum: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install latest apache and php fake
    apt:
       name:
         - apache2
         - libphp
       state: latest
       update_cache: yes
    when: ansible_distribution == "Ubuntu" 	

