---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install latest apache package with php
    tags: apache,Amazon,httpd
    yum: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: install latest apache and php fake
    apt:
       name:
         - apache2
         - libphp
       state: latest
    when: ansible_distribution == "Ubuntu" 	

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    yum:
      name: samba
      state: latest
