---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install latest apache package with php
    tags: apache,Amazon,httpd
    yum: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: copy default html file for site
    tags: htppd, apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    yum:
      name: samba
      state: latest
